### ISSUE TITLE
Hello, my name is Mingming  Huang, Do you have a version of iperf2?

### ISSUE THREAD

**Issue by JonkMing** [ndfred/iperf-ios#1]
Hello, my name is Mingming  Huang, Do you have a version of iperf2?
My Android  version is Iperf2.You  project version is Iperf3.

**Comment by adrianmihalko** [comment]
Hi, still not released on AppStore?

**Comment by ndfred** [comment]
iperf3 is bi-directional, which makes it possible to test both upload and download performance. I use that to make sure my power level are adjusted correctly (up should match down in that case). iperf2 doesn't allow that and is inferior in many cases. I'm sure you can find an iperf3 client for Android.

I don't feel comfortable releasing such a crude version in the AppStore, and wouldn't have time to maintain it (I know it hangs in some cases which I haven't had the time to look into). If you would like to reuse the code to do that then feel free, the license is very permissive.

**Comment by JonkMing** [comment]
I feel very bad at the app store

**Comment by JonkMing** [comment]
Thanks for your answer. I just didn't find iperf2's library file
