### ISSUE TITLE
UDP Failure

### ISSUE THREAD

**Issue by Farizzle** [ndfred/iperf-ios#3]
Attemping to set the protocol to UDP via the method -

set_protocol(test , 2);

Sets all the test protocol items correctly for UDP (analysed through breakpoints). But socket writing always fails, and sometimes mentions No such File or directory exists?

**Comment by ndfred** [comment]
There are a ton of weird crashes in the app, and I'd like to release it at some point to get more crash reports. @Farizzle: what is your usecase? Using the iperf library and glue code from this repo to run UDP tests?

**Comment by ndfred** [comment]
Closing this as I'll need to rework the app to get UDP to work

**Comment by JaredTHarden** [comment]
Hello @ndfred is UDP something you still plan on implementing?

**Comment by ndfred** [comment]
It isn't planned because I am not really seeing demand for it and the UI
work to get this done is quite involved, what would your use case be?
