### ISSUE TITLE
Error while integrating iperf 3.0 files

### ISSUE THREAD

**Issue by ajsagar92** [ndfred/iperf-ios#38]
![Screenshot 2020-10-22 at 2 41 49 PM](https://user-images.githubusercontent.com/22812738/96854492-fab72300-1474-11eb-80da-dc3b3cc29d67.png)
Hi,

I am integrating iperf in framework I am developing in objective c for iOS and macOS. After copying source files of iperf3.0 (c files), I am getting error on iOS/macOS system files like NSObject, AppKit.h etc. I am not sure what I am missing. But iperf files showing error for arm64 like in screenshot attached.

Universal Framework Minimum Target:
iOS: 11.0
macOS: 10.11

Shared code for iOS and macOS framework developed mainly in Objective C

**Comment by ndfred** [comment]
It looks like you have a PCH or something that if you include in a C file will barf. Just disable it for these files, or use a macro to only include Objective-C headers in your PCH if you're dealing with an m or mm file. Closing as it's not really related to the project.
