### ISSUE TITLE
Unable to connect to host message when using IPv4 address

### ISSUE THREAD

**Issue by salamander-in-steinachtal** [ndfred/iperf-ios#40]
When using an ipv4 address as opposed to hostname I receive the message „unable to connect to server“. The resolvable hostname works fine the server has both an ipv4 and IPv6 address - the IPv6 address works too

**Comment by ndfred** [comment]
First time I've had that report. The app is not doing any validation on an IPv4 address (since you can enter anything in that field really), maybe it has been misspelled, a space at the end or something? I primarily use IPv4 addresses and have no issue really.

**Comment by salamander-in-steinachtal** [comment]
Thanks for looking - no spaces/junk were present - issue is highly intermittent I’ll re-open if I can reliably recreate
