### ISSUE TITLE
running test doesn't seem to do anything

### ISSUE THREAD

**Issue by pfalstad** [ndfred/iperf-ios#48]
I am using an Ipad pro running 14.4.1, connecting to a server running on a mac.

Transmit mode upload, streams 1, test duration 10s.

I click start and I get "unknown error 114 running the test".  I try again and get the same error.  I try again and this time no error..  I just get "..." displayed below.

I wait 10 seconds and nothing happens.  I click "Stop", nothing happens.

The server logs indicate it's connecting, but almost nothing is sent:

```
------------------------------------------------------------
Server listening on TCP port 5001
TCP window size:  128 KByte (default)
------------------------------------------------------------
[  4] local 192.168.1.6 port 5001 connected with 192.168.1.123 port 52998 (peer 112.28467.27250-unk)
[  5] local 192.168.1.6 port 5001 connected with 192.168.1.123 port 52999 (peer 98.30308.30839-unk)
[  6] local 192.168.1.6 port 5001 connected with 192.168.1.123 port 53000
[ ID] Interval       Transfer     Bandwidth
[  4]  0.0-62.4 sec  37.0 Bytes  4.75 bits/sec
[  5]  0.0-62.4 sec  37.0 Bytes  4.75 bits/sec
[  6]  0.0-62.4 sec  37.0 Bytes  4.75 bits/sec
[SUM]  0.0-62.4 sec   111 Bytes  14.2 bits/sec
```

I also tried download, and I got error 114 6 times, and then the "..."

**Comment by pfalstad** [comment]
I was using a server running iperf 2.

**Comment by ndfred** [comment]
That's right, see the [documentation](https://github.com/ndfred/iperf-ios/blob/master/Documentation/Help.md) for how to install and run iPerf3
