### ISSUE TITLE
App is no longer available on the App Store

### ISSUE THREAD

**Issue by pges-wings** [ndfred/iperf-ios#49]
hello, I recoverd my iphone and I can't download it. does it still offered in AppStore?

**Comment by ndfred** [comment]
Hi! I think I've let my Apple Developer account run out, I'll refresh that and the app should re-appear. Thanks for letting me know :)

**Comment by ndfred** [comment]
The app is back up, thanks again for reporting this @pges-wings! Hoping to have a new version out soon.
