### ISSUE TITLE
App unavailable in the App Store

### ISSUE THREAD

**Issue by kocoman1** [ndfred/iperf-ios#57]
in the app store, what region do I have to set to download it? thx

**Comment by ndfred** [comment]
Just logged into my Apple developer account and sure enough:
> Your Apple Developer Program membership has expired
I'll sort this out today, and will try to release an updated version of the app if I can dig myself out of generating new certificates, thanks for the ping!

**Comment by bb** [comment]
Great, thank you!

**Comment by ndfred** [comment]
Renewed my dev account and tried to reinstall the app, cannot see it in the App Store (probably their cache) but it shows as ready in App Store Connect. Let me know if it works for you!

**Comment by bb** [comment]
It took about 10 minutes since your message... now it's here (German App Store, but I see it's also others, at least in US and Fr): https://apps.apple.com/de/app/iperf-3-wifi-speed-test/id1462260546

Thanks a lot!

**Comment by bb** [comment]
By the way, I got the recommendation from this video: https://youtu.be/kMgs2XFClaM?t=1165

**Comment by fuomag9** [comment]
App is still not available, I can publish it if you want
